### ISSUE TITLE
Sending a new sms to an existing contact

### ISSUE THREAD

**Issue by Spidored** [jlippold/WifiSMS#10]
When i use the "+" to start a new conversation with a contact.

I select the contact, tapping my text, but it send the text to the wrong number, i explain how it's happen.

My contact is registered by this string : "+32495123456"
My prefix option in WifiSMS is "+32"

For the name/picture it make the good replacement, and when i reply to a text it work too.

But when i starting a conversation, it send to "32495123456" and that reached no one =).

I think the issue can be corrected by handling the "+" in the whole app.

**Comment by treason** [comment]
Understood... i'll see what I can do.

**Comment by treason** [comment]
fixed i think

**Comment by Spidored** [comment]
mhh, for now i don't have my contact anymore in the <SELECT>, it's totally empty

**Comment by treason** [comment]
I don't understand dude

**Comment by Spidored** [comment]
a illustration is always better than a long discuss... so

http://91.121.64.155/~ftpedwin/emptywifisms.png

My list is empty in ur last commit 1.0.5r

**Comment by treason** [comment]
Ohh ok. Give the page a full refresh. It's not a select list any more. It's an input box

**Comment by Spidored** [comment]
lol sorry, i wroted "mhh, for now i don't have my contact anymore in the <   SELECT   >, it's totally empty" in the other post, but the <... ...> replaced =)

**Comment by Spidored** [comment]
Oh yeah, sorry it work as well ^^

I had refresh but i had replace the func.js with the smiley edited one. So ur edit wasn't applied on my side xD

That was it fail. 

A cool thing could be this style : 
http://91.121.64.155/~ftpedwin/coolstyle.png

i think it's not pretty hard to do with jquerry effect.

**Comment by treason** [comment]
yea that would be nice, but im not sure if the plugin I am using supports it... maybe next version. New deb just posted with the smiley fix included

**Comment by treason** [comment]
yea imma submit to bigboss.. I think im done, hopefully its bug free
