### ISSUE TITLE
Handling the "smileys"

### ISSUE THREAD

**Issue by Spidored** [jlippold/WifiSMS#11]
Here it's a graphical issue,

in biteSMS the strings ":) :-) :( :-( :D :-D xD, ..." are replaced by smileys. 

Smileys listing are : http://assets1.delicioussms.com/images/biteSMS-feature-fw3-add-contact.jpg?1312868206 
:-D :D :d :-d
:-( :(
;-) ;)
:-|| 
;-( :'(
^^
:-*
:-P :-p :p :P
:-$ :$
:-O :O :-o :o
(L) <3
:-] 
:-X :x :X :-x
XD xD Xd (and all variants with "-" x maj/min and d maj/min)
:-S :-s :S :s
:-) :)
:-| :|
.>
:-/ :/

There certainly others string to make some smileys below, but i don't know them, and there's no list on biteSMS. So... we can start with that base and when someone figured out other strings adding them.

**Comment by jasonchutko** [comment]
The problem I see with this is that it is not how the official SMS app handles emoticons. Are you also suggesting it sends an Emojii instead of the text, or just display it?

**Comment by Spidored** [comment]
it's not emoji, it's just a display (replace text string with the image). inside my native SMS app the smileys are the same. but i think it's iPhone delivery who handle that and not builtin Apple features

**Comment by jasonchutko** [comment]
Furthermore on that note, only iPhone (afaim) has Emojii support, therefore we could not force the replacement in the message box.

**Comment by treason** [comment]
yea this would have to be a client side only replacement on incoming SMS only. Its not a good idea to do this on outgoing because not all devices support emoji.

**Comment by Spidored** [comment]
that's what i mean, only string replace at the display. sorry if my explanation were bad ^^

**Comment by treason** [comment]
Hey @jrcdude, do you want to take this one? I think all you have to do is modify the checkforemoji() function in the func.js file.

**Comment by treason** [comment]
@Spidored it means that the webpage will convert :-) to emoji on incoming sms only, not on outgoing sms

**Comment by jasonchutko** [comment]
I'll take a look :P  Will have to do a Regex on the string for URL's though so http:// for example won't recognize the :/.  I'm still more for a WYSIWYG approach though, if they didn't send Emojii, it shouldn't be displayed as Emojii.

**Comment by jasonchutko** [comment]
Where can I get a reference of the Emoji characters' character codes?

**Comment by treason** [comment]
its in the func.js at the very bottom. a huge if else

**Comment by jasonchutko** [comment]
I mean like so I can see that a :P = E008 for example (which it doesnt)
Edit: NVM, found it here:
http://www.intatters.com/misc.php?do=showsmilies
Edit 2: Damn, only a partial list -.-
Edit 3: http://pukupi.com/post/1964/ Looks good :)

**Comment by jasonchutko** [comment]
https://github.com/jrcdude/WifiSMS/commit/4dfea06d6f5c8651d19dc6812dd4de0bc812ca87#diff-0

Works great in my test window, but when implemented into the func.js, I don't think it is catching all the emoticons to be transformed into the Emoji.  Can I have a test of this please?  You can install it right over top of func.js in:
/private/var/mobile/Library/WifiSMS/Web/
by SSH'ing in.

**Comment by Spidored** [comment]
That's perfect, just one "bug", it don't replace regex in all case (only when it's distached from the rest), i mean: 

imagine that message 
"hello, how are u ? ^^" >>> ^^ will be replaced.
but that one
"hello, how are u ?^^ " >>> ^^ will not be replaced.

i think the regex should match the string in other string and not only the string itself (sorry i explain really bad, poor english xD)

**Comment by treason** [comment]
Ohh I don't know dude. I guess it's up to us.

**Comment by jasonchutko** [comment]
Oh damn..  THAT's why.  I only removed the one's with a space preceding them to remove odd cases..

**Comment by treason** [comment]
So u are saying only replace when preceeded by an empty space right?

**Comment by jasonchutko** [comment]
Yes, for example: "Lol :P" replaces, "Lol:P" does not, and ":P" does not.  I can remove the space requirement, not sure how that will handle in odd situations though?

**Comment by jasonchutko** [comment]
https://github.com/jrcdude/WifiSMS/commit/8353b2eaf723518685ffc28f4c9f2d12b1262246

is better suited to your liking.  I also omitted some of the ones from your list, as I couldn't find suitable images from:
http://pukupi.com/post/1964/ 

if you write out the emoticon and the code, I can add it after.

**Comment by Spidored** [comment]
i see that u had add 12 regex, but there's a total of 20 smileys  ^^
There's thoses missing : 

:-|| >>> red angry face
:-\* >>> Kiss
:-] >>> http://assets1.delicioussms.com/images/biteSMS-feature-fw3-add-contact.jpg?1312868206 next to the <3
:x >>> with the white thing on the mouth
xD >>> do i have to explain ? :p
:s >>> do i have to explain too ? ^^
:| >>> first of the last row
??? >>> broken heart i can't get the ascii code, don't know why there's some char who bug. i'll check on the sms.db directly

> .> >>> just before the last
> :/ >>> the last

**Comment by Spidored** [comment]
ups i had closed xD, so i found finaly the code in sms.db, don't know why it doesn't appear on the WifiSMS but still... this is </3 simply.

**Comment by jasonchutko** [comment]
If you could just grab me the code like:

#&xe417 from the chart:
http://pukupi.com/post/1964/
(All I need is the e417) for each one, I can quickly add this later when I get back on the computer :)

**Comment by Spidored** [comment]
yep so here it is,

:-||                        & #xe416;
:-\*                     & #xe418;
:-] :]                      & #xe402;
xD XD Xd x-D X-D X-d        & #xe409;
:s :S :-s :-S               & #xe407;
:| :-|                      & #xe40d;
</3                     & #xe023;

> .>                         & #xe40e;
> :/ :-/                      & #xe403;

(i set a space between & and # to avoid the char replace in the comment)
There's certainly some other string to do that smiley, but i told who wich i known

**Comment by Spidored** [comment]
-    regArray[4][0] = new RegExp(/ ;-?(/g); // ;(, ;-(
-    regArray[4][1] = "E411";
  +
-    regArray[5][0] = new RegExp(/ :'(/g); // :'(
-    regArray[5][1] = "E411";

This one is 411, not 401 ^^ (still from biteSMS source)

**Comment by jasonchutko** [comment]
Alright thanks for the heads up and info :) I'll add that later!

**Comment by treason** [comment]
I'm just about to release one last build for the weekend. Is this completed?

**Comment by jasonchutko** [comment]
It's working, not all emoticons are added though, mainly the important ones.

https://github.com/jrcdude/WifiSMS/commit/b7916d31e740384ec31f9eb57e7a031469a33907

is the latest commit.

**Comment by Spidored** [comment]
@jrcdude, here's the entire code for ur further commit :

var regArray = new Array(22);

```
    var i = 0;
    for (i=0; i < 22; i++)
    {
        regArray[i]=new Array(2);
    }

    regArray[0][0] = new RegExp(/:-?\)/g); // :), :-)
    regArray[0][1] = "E056";

    regArray[1][0] = new RegExp(/:-?P/gi); // :p, :P, :-p, :-P
    regArray[1][1] = "E105";

    regArray[2][0] = new RegExp(/:-?\(/g); // :(, :-(
    regArray[2][1] = "E058";

    regArray[3][0] = new RegExp(/;-?\)/g); // ;), ;-)
    regArray[3][1] = "E405";

    regArray[4][0] = new RegExp(/;-?\(/g); // ;(, ;-(
    regArray[4][1] = "E411";

    regArray[5][0] = new RegExp(/:'\(/g); // :'(
    regArray[5][1] = "E411";

    regArray[6][0] = new RegExp(/\^\^/g); // ^^
    regArray[6][1] = "E415";

    regArray[7][0] = new RegExp(/:-?\$/g); // :$, :-$
    regArray[7][1] = "E414";

    regArray[8][0] = new RegExp(/:-?o/gi); // :o, :O, :-o, :-O
    regArray[8][1] = "E107";

    regArray[9][0] = new RegExp(/\(L\)/g); // (L)
    regArray[9][1] = "E022";

    regArray[10][0] = new RegExp(/:-?d/gi); // :d, :D, :-d, :-D
    regArray[10][1] = "E057";

    regArray[11][0] = new RegExp(/<3/g); // <3
    regArray[11][1] = "E022";

    regArray[12][0] = new RegExp(/:-?\|\|/g); // :-||, :||
    regArray[12][1] = "E416";

    regArray[13][0] = new RegExp(/:-?\*/g); // :-*, :*
    regArray[13][1] = "E418";

    regArray[14][0] = new RegExp(/:-?\]/g); // :-], :]
    regArray[14][1] = "E402";

    regArray[15][0] = new RegExp(/x-?d/gi); // xD, XD, Xd, x-D, X-D, X-d
    regArray[15][1] = "E409";

    regArray[16][0] = new RegExp(/:-?s/gi); // :s, :S, :-s, :-S
    regArray[16][1] = "E407";

    regArray[17][0] = new RegExp(/:-?\|/g); // :-|, :|
    regArray[17][1] = "E40D";

    regArray[18][0] = new RegExp(/<\/3/g); // </3
    regArray[18][1] = "E023";

    regArray[19][0] = new RegExp(/>\.>/g); // >.>
    regArray[19][1] = "E40E";

    regArray[20][0] = new RegExp(/:-?\//g); // :-/, :/
    regArray[20][1] = "E403";   

    regArray[21][0] = new RegExp(/:-?x/gi); // :x, :X, :-x, :-X
    regArray[21][1] = "E40C";


    var p = 0;
    for (p= 0; p < 22; p++)
    {
        out = out.replace(regArray[p][0], "<img src='" + targetToBase64(regArray[p][1]) + "'>");
    }
```

+++++++++++++++++++++++++++++++++
+++++++++++++++++++++++++++++++

But we have a problem, for the smiley xD (E409) when the image is replaced, on the smiley code ref : 
if( target =="E409" ){ base64 =  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAENUlEQVQ4ja2UaWxUVRiGn3OXTmlLy9hhSktbKMWUUJA2LYWAxeovkE2iQTQWBBN/GOMCISYQ4y9NVGKCSyAxEA2iiKLBpCKBEMAEWVoL2MpmQQbodGiZ6Sydzp17537+mDa4kfjDL3mTk7M8+U7Oe174n0vda2H8GCa0lLFwXjkPPVBGPcD5XjpP3OTY0V5+6B+m7z8Bc3XyXprFphcX5b3sb5xdYEyahyqqBECiAZzrJ7jdfibx4YHk1vfP8VYqQ/Ke3ZbkUX5wJe3Wvjkiwb0iyXMiiQ6R6MmsEh3ZueBesfbNkYMraS/Jo/zPjY0OVIHJuO9WqeMLnmmZoTeuBzsNdgyQf17KLAQzh0z7exz/7GjXsj2yIGEzCIg+skt/Y57a+tTqSQuNhrVg90OqF5w4ZP5Fdj+4MTT/dMrzLvi1W9HiIwHaRoFaVSG1Hz+Xuz2/ca42lNSIh66R53Ozh61BcGJZZWJgJMEzzJ2rvyOORa7XYIYRmLX3tPPNoMWADhhratUrSx8d16z5y3Bciy/arnDs+06mlgn54x1IDmbh+SluX+1l+7afuBJKUjfNwNQtTLtfu35xOH4qyFEd8GxoNjfNmFtUqXTBJEFjYw66SvDO2x3EgiFmTRsCZ4BdOy+w49NuVqzw8tgiL2YqAukoCotEYFi+6nZ3G4A5sVgrwTTBioG4ADRUCEUeEzw6qJG38+gUeUwaKgTivZAAdA1yTCYWayWAqQGGUijJOIjrgMoQCdps3BJiaauf1jWFkE5BOkXr2kKWtvrZuCVEJGiDlsF1HMR2UAoFGAYgfVEnLOkEYih03aEnnuHVDQaVFTGIR2DMiBdi8HCzTnWVwdVQmIZiHXEMJC30RZ0wIAZgn7nmdi2x0k2mV+FmbBrrXChyQRO4T+461gUcRWWNonKChoQ1dI+LHRHOXHO7ANsArP2X5cDmAXetOc1Uxw4qdn3gUlsn5HgFMx/IzQIlCfaQkA5Dd6fLC6/rzG7SsLps2X9ZDgCWDkh/kliV7s6sn25WVzXpBC8J4d8ymOfLWdX5ILlniyntnMz8X2o4ez3FYCpOfXMOi9eYSAB27Ukd3tkpHwHR0Z9inboht5aUsnD8FCO//gmDy+E0eriOlqbnKb1/CqVTaxlbPZ+f3Sv4lt1g3WtjIKS4eCjdv/pzZ8OQzQXAGQW6QzaDh7szPS0FMn+CXy9oWJQGt4GJZU8jk8aiykvR/NXoM0+yeN1F6Mmhq80KPb7NXh+I8SNZEzEKBEjdGabv6w63fWyf46vxSFU6PlX5vMthnKDle1BGIbFEG2bokvvJDufQs7szm0dgd0ZT5O95qIBCoHy6jzmPVBY8srF684oyX0UeQO/AjeS7PW9+eySQOPLrAKeAm1kz3Y2keyW2BngBX01uYdOT3snLQfgyEth/KRU9DQwAkREj/aX+AOdC7fDEM6chAAAAAElFTkSuQmCC';}

There's an "xd" on that, so it completely messed the display...

We need to find a way to avoid the replacing inside the <img>

**Comment by Spidored** [comment]
sorry, the problem isn't inside the E409 code, but in the other who contains "xd" or "XD". ans there's a lot :s

**Comment by jasonchutko** [comment]
Yeah see :P That's why I previously made it so there had to be a space before it.  Also,

3 & #xe023;
you wrote above, can you correct the 3 to its proper emoticon text form?

**Comment by treason** [comment]
ok dokie.. thanks

**Comment by Spidored** [comment]
The 3 was </3, i wrote it correctly but i don't know why it bug, when i edit my post it's been </3 but it display only "3" :s

Maybe we can check the string lenght without space, if there's more than 3 char without space >>> it can't be a smiley so don't try to replace ?

**Comment by Spidored** [comment]
So, here is the correct code (but the xD will only work with a space so)

```
    var regArray = new Array(22);

    var i = 0;
    for (i=0; i < 22; i++)
    {
        regArray[i]=new Array(2);
    }

    regArray[0][0] = new RegExp(/:-?\)/g); // :), :-)
    regArray[0][1] = "E056";

    regArray[1][0] = new RegExp(/:-?P/gi); // :p, :P, :-p, :-P
    regArray[1][1] = "E105";

    regArray[2][0] = new RegExp(/:-?\(/g); // :(, :-(
    regArray[2][1] = "E058";

    regArray[3][0] = new RegExp(/;-?\)/g); // ;), ;-)
    regArray[3][1] = "E405";

    regArray[4][0] = new RegExp(/;-?\(/g); // ;(, ;-(
    regArray[4][1] = "E411";

    regArray[5][0] = new RegExp(/:'\(/g); // :'(
    regArray[5][1] = "E411";

    regArray[6][0] = new RegExp(/\^\^/g); // ^^
    regArray[6][1] = "E415";

    regArray[7][0] = new RegExp(/:-?\$/g); // :$, :-$
    regArray[7][1] = "E414";

    regArray[8][0] = new RegExp(/:-?o/gi); // :o, :O, :-o, :-O
    regArray[8][1] = "E107";

    regArray[9][0] = new RegExp(/\(L\)/g); // (L)
    regArray[9][1] = "E022";

    regArray[10][0] = new RegExp(/:-?d/gi); // :d, :D, :-d, :-D
    regArray[10][1] = "E057";

    regArray[11][0] = new RegExp(/<3/g); // <3
    regArray[11][1] = "E022";

    regArray[12][0] = new RegExp(/:-?\|\|/g); // :-||, :||
    regArray[12][1] = "E416";

    regArray[13][0] = new RegExp(/:-?\*/g); // :-*, :*
    regArray[13][1] = "E418";

    regArray[14][0] = new RegExp(/:-?\]/g); // :-], :]
    regArray[14][1] = "E402";

    regArray[15][0] = new RegExp(/ x-?d/gi); // xD, XD, Xd, x-D, X-D, X-d
    regArray[15][1] = "E409";

    regArray[16][0] = new RegExp(/:-?s/gi); // :s, :S, :-s, :-S
    regArray[16][1] = "E407";

    regArray[17][0] = new RegExp(/:-?\|/g); // :-|, :|
    regArray[17][1] = "E40D";

    regArray[18][0] = new RegExp(/<\/3/g); // </3
    regArray[18][1] = "E023";

    regArray[19][0] = new RegExp(/>\.>/g); // >.>
    regArray[19][1] = "E40E";

    regArray[20][0] = new RegExp(/:-?\//g); // :-/, :/
    regArray[20][1] = "E403";   

    regArray[21][0] = new RegExp(/:-?x/gi); // :x, :X, :-x, :-X
    regArray[21][1] = "E40C";


    var p = 0;
    for (p= 0; p < 22; p++)
    {
        out = out.replace(regArray[p][0], "<img src='" + targetToBase64(regArray[p][1]) + "'>");
    }
```

**Comment by treason** [comment]
Would you guys try the beta before it goes public? thanks http://t.co/jWeqQAk

**Comment by jasonchutko** [comment]
Added all your requests, and fixed the xD:

https://github.com/jrcdude/WifiSMS/commit/9e2e0e7ede9321336764ddbcdb8cd89da283b7c0

**Comment by Spidored** [comment]
@treason , 

yes, i will ^^, i still need to figured out why some sms i sent bug (like i explain in the other issue)

**Comment by jasonchutko** [comment]
Alright I think its only the ones with xd that have the problem, as that is the only string that occurs in the base64 images.  Merge my new code, and I don't think there will be any bugs ;)

https://github.com/jrcdude/WifiSMS/commit/9e2e0e7ede9321336764ddbcdb8cd89da283b7c0

**Comment by Spidored** [comment]
```
 regArray[12][0] = new RegExp(/:-?\@/g); // :@

 regArray[12][1] = "E416";
```
-    regArray[12][0] = new RegExp(/:-||/g); // :-||
-    regArray[12][1] = "E416";

?? ^^ u reset the 12

and u forgot that one

```
regArray[21][0] = new RegExp(/:-?x/gi); // :x, :X, :-x, :-X
regArray[21][1] = "E40C";
```

For xD, yes it's the only smiley with 2 letters, other is with ":" or else special char. so no prob ^^

**Comment by jasonchutko** [comment]
https://github.com/jrcdude/WifiSMS/commit/e09b657039f76cfc33a7f2c16743ddefd60cea5f

Check that one out for me please?? Think I fixed all?

**Comment by Spidored** [comment]
ok checked ^^ it's good

**Comment by treason** [comment]
Test the beta for me dudes

**Comment by jasonchutko** [comment]
Update the code!!  Other one is buggy!  Or are you not able to make a new .deb tonight?

https://github.com/jrcdude/WifiSMS/commit/e09b657039f76cfc33a7f2c16743ddefd60cea5f

**Comment by treason** [comment]
ok new deb posted. Would you test the new shit in the changelog. i.e message deletion, downloading, auto complete etc... thanks

**Comment by Spidored** [comment]
@treason i'll do this tomorrow morning (it's 3:33 for now here xD i gotta sleep a bit)

**Comment by treason** [comment]
lol ok cool... once tomorrow comes i'm done... real life job takes over until next weekend. Thanks for all your help

**Comment by jasonchutko** [comment]
I'm gonna check it in a little bit, sorry I'm a little busy :P

**Comment by treason** [comment]
no worries, i think its fine. Submitted 1.0.5 to bigboss
