### ISSUE TITLE
Unable to View in Browser

### ISSUE THREAD

**Issue by thetaz01** [jlippold/WifiSMS#2]
I am Currently running an iphone 4.0 with iOS 4.3.3
Running Windows 7(64) 
And when i open the browser and point to the ip and port, it comes up disconnected i click it, it says connected but never get anything on the screen..  other than the gray bar down the left side..
I tried it in Google Chrome, Firefox, and also on my imac with safari..
what am i missing..
Also Just a side note, i have BiteSMS installed NOT sure if that posses a problem, so i closed BiteSMS and openend the native SMS app, and still doesnt work..

thanks
PS awesome idea :) i too work at my desk and am an IT network manager, being able to text to my iphone from my desk is awesome cant wait to get it working

**Comment by treason** [comment]
Did you try to reboot the phone?... sometimes comm center needs a restart.

**Comment by thetaz01** [comment]
Thats the first thing i tried.. :-/
HAHA, you sound like me.. Im a IT Network Manager, FIRST thing i ask peopel when they bother me is.. "Did you Reboot!" LOL HAHA

**Comment by treason** [comment]
lol.. its always step one isnt it? What device/what OS? Also if you load up firebug do you get any errors in the console?

**Comment by thetaz01** [comment]
LOL it sure is...
and I am Currently running an iphone 4 with iOS 4.3.3
 Running Windows 7(64) Also Just FYI, i have BiteSMS installed.. i tried shutting that down and using the native SMS app and it still doesnt work...
And I tried opening in Firebug, Im not very familiar with it Never used it, but figured it out pretty quick..
I get a POST http://192.168.1.122/ajax/ 200 OK 6.4s and if i open that up i see data of all my contacts, 
then i click connect, and i get another POST http://192.168.1.122/ajax/ 200 OK 731ms
and if i open and expand the first one i see all my contact data, and the same with the second one i see my messages..
BUT the screen on the browser, is just a write vertical box along the left side and a gray box on the right, with the green connected dot..

**Comment by treason** [comment]
ok for the first POST, there should be two parts. "AddressBook" and  "WithSMS"... do you have data in both? data is only loaded when the contact is in your address book, and you have a conversation started in the SMS.db. Furthermore the number in both sections should match.

**Comment by thetaz01** [comment]
From what i can see, in the first post i do have an 
{"AddressBook" : [ 
And then further down "WithSMS" : [ {
 
Then in the second post i have 
{"messages" :[
 

 
----- Original Message -----

**Comment by treason** [comment]
ok try this copy the entire string starting at the first { and ending at the last } and paste it into jsonlint.com

Do it for both POSTS

Tell me if jsonlint says its valid JSON

**Comment by thetaz01** [comment]
Ok, SO!! i found the problem...
I had two Contacts that at ONE point used the iphone garmin App to navigate tothere house... and when i did that, It put a 
{
            "<GarminPointlat="0.736695770"lon="1.295267760"><name>HunterMountain</name></GarminPoint>": " Hunter Mountain"
        }
    ],
As a contact 
and the error came up as
Parse error on line 790:
...  "<GarminPointlat="0.736695770"lon="1.2
-----------------------^
Expecting '}', ':', ',', ']'
So i deleted those contacts, cause i couldnt find on the outlook contact where it stored that.. so i just deleted them, and it then started working...
 

----- Original Message -----

**Comment by thetaz01** [comment]
Hey FYI, i forgot, i was wrong it WASNT an Iphone garmin app, it was an OLD windows mobile garminapp. that doesnt work anymore.. So its actually NOT AN ISSUE with an iphone UNLESSS someone ported there contacts from an old windows mobile.. just so you know in case you see this again..

thanks again
Awesome awesome APP!!

----- Original Message -----

**Comment by thetaz01** [comment]
Also Just a little more info, just incase ur intersted.. The Field in which the info was stored, was an OUTLOOK contact, and the field was "Radio Phone" But again, not sure if anything uses that anymore.. 
Also so far i love the app, absolutely great!!! i would like to know if there are any plans to or if its even possible to be able to reset the UNREAD counts on the phone, since u read them on the website, it doesnt clear the tick mark over the mesages bubble, nor does it clear the unreads from each SMS u receive??
?? is that possible?! :)
thanks again

**Comment by treason** [comment]
Yea im working on the unread part. So which character was breaking it? the double quot? or the = sign? or the "<" ?

**Comment by thetaz01** [comment]
Awesome.. and 
Heres what the debugger said
Parse error on line 790:
...  "<GarminPointlat="0.736695770"lon="1.2
-----------------------^
Expecting '}', ':', ',', ']'

**Comment by jasonchutko** [comment]
I also have this issue, restored iPhone and the problem persisted.  I didn't re-import my SMS messages, just my contacts.
http://cl.ly/2m3C2f0H060n1s3g1w2k
is what it looks like?

**Comment by jasonchutko** [comment]
Alright I fixed my problem, it also existed in the contacts as an invalid JSON response:

The format was:

{
            "2347023473
\" : "RandomInfo" }

So the backslash that existed was causing it.

**Comment by treason** [comment]
I thought I escaped that backslash? Well thanks for the heads up

**Comment by jasonchutko** [comment]
The problem was that you did escape the backslash, therefore adding it to the string.  When you put the string into the JSON string, you also added a backslash before a quotation mark, therefore escaping that quotation mark, and then messing up the JSON response.  So my bugfix should fix that problem :) .. I think ;P
