### ISSUE TITLE
International sending

### ISSUE THREAD

**Issue by chrisbmc34** [jlippold/WifiSMS#3]
So I'm located in Iceland. I've tried entering the country code, as well as full phone number every possible way imaginable, yet I can't send sms out. I believe others are having issues with international sending, too. Any advice?

**Comment by treason** [comment]
yea im working on this also, hopefully this weekend. I am unable to code on weekdays due to my real life job.

The way I handle international CC's is way off. I think I always add a + sign, strip the leading 0, then add the CC, then append the number.

This works fine for the USA, but I dont think the + / 0 thing works for you. So, just wait for the next version.

**Comment by chrisbmc34** [comment]
Thanks. You're pretty awesome. Waiting until this weekend makes me regret moving abroad.

**Comment by treason** [comment]
can you try version 1.0.4?

**Comment by chrisbmc34** [comment]
Yeah. Has it been released?

## 

Chris McClure

On Sat, Aug 6, 2011 at 4:10 PM, treason
reply@reply.github.com
wrote:

**Comment by treason** [comment]
yes, give it a full uninstall, then try this version here: https://github.com/treason/WifiSMS/tree/master/Build/deb

**Comment by chrisbmc34** [comment]
Perfect. Definitely doesn't work with explorer, as nothing should. Yet
it seems to be very slow in Firefox, not connecting some times--needs
a few refreshes. Definitely works best on chromes. There was some lag
at first, but it seems as if it gets better after it loads.

Second question-- is there a way to send mms through wifisms?

Awesome update!!! Got girlfriend using it, too. Going to be a lifesaver at work.

ps... I noticed on Cydia that this release still syas 1.0.3, thus I
didn't receive a notification to update. Definitely good to go!

## 

Chris McClure

On Sat, Aug 6, 2011 at 4:40 PM, treason
reply@reply.github.com
wrote:

**Comment by treason** [comment]
thank you chris. I think I will submit to bigboss soon. So far you are the only user who was able and willing to install this.

Thanks

**Comment by chrisbmc34** [comment]
no problem. let me know when you have any updates in the future.

## 

Chris McClure

On Sat, Aug 6, 2011 at 5:08 PM, treason
reply@reply.github.com
wrote:

**Comment by treason** [comment]
Updated again on github and submitted to bigboss
