### ISSUE TITLE
missing conversations

### ISSUE THREAD

**Issue by ghost** [jlippold/WifiSMS#4]
im not sure if its because i use bitesms or something else,
but _most_ of my SMS conversations do not appear in WifiSMS's web interface.

other than that, the app is awesome!

**Comment by treason** [comment]
im on it

**Comment by treason** [comment]
can you try 1.0.4 ? https://github.com/treason/WifiSMS/blob/master/Build/deb/WifiSMS-1.0.4.deb

**Comment by ghost** [comment]
stilling missing most of the conversations.
also, the order they are listed in wifi makes no sense. people i didnt talk to for weeks are at the top of the list, while people i just talked to aren't even there.

**Comment by treason** [comment]
Yea the deb was fucked up for 1.0.4... but as far as the dates, that is computed by your system time on the computer.

**Comment by ghost** [comment]
still it shouldn't matter. the date and time on my iphone and pc are the same.
it must be something with WifiSMS, it's simply ignoring some of my contacts and not listing them..
i must say once again the idea is fu... awesome.

**Comment by treason** [comment]
i was talking about the "sort" that didnt make sense, not the missing conversations. The last deb I posted was fucked, but this new one seems ok.. https://github.com/treason/WifiSMS/blob/master/Build/deb/WifiSMS-1.0.4.deb Make sure wifiSMS is off before you reinstall the deb, and let me know

**Comment by ghost** [comment]
this .deb is rather small. running wifisms through sbs after installation doesnt listen on :8080.

**Comment by treason** [comment]
it worked for me... maybe you need to uninstall/respring/reinstall?

**Comment by ghost** [comment]
been through all of that. still no go :(

**Comment by treason** [comment]
hmm this is not making sense... how are you installing via autoInstall or iFile? is it not running at all? can you run the app via terminal add see what it says? Type this into putty or terminal on the iphone: sudo -u mobile /private/var/mobile/Library/WifiSMS/WifiSMS

**Comment by treason** [comment]
i think the issue is on your end ducch. other users installed it fine including myself. But I would really like to know if your bugs are fixed.

**Comment by Malott21** [comment]
Ducch.. If you have ifile or ssh.. 

Go into the iPhone's file system and navigate to Private/Var/Mobile/Library/

In there look to see if you have a folder that is called "WifiSMS" 

If not you need to have that folder in there before it will even connect on the :8080 port.

**Comment by Malott21** [comment]
--  Go ahead and download >  http://www.mediafire.com/file/otgz981kfxc0v40/WifiSMS.zip

-- Just place it in this directory on iPhone >  Private/Var/Mobile/Library

Extract it in there using ifile or ssh it in there. Then try and connect and it will or should work.

(Until he fixes deb or figures out what the issue is here)

**Comment by treason** [comment]
yea so i think i fixed it now.. The control file in bigboss was diff than mine. should be a good deb now

**Comment by ghost** [comment]
looks ok now. awesome work ;')
cant wait on some whatsapp implementation ^^

**Comment by treason** [comment]
Cool thanks. I don't get the whole whatsapp thing. I fail to see the advantage. Explain how this can be beneficial

**Comment by ghost** [comment]
whatsapp is same thing like the sms system,
just over the internet and using their servers to exchange the text and such.
its a very popular one and used by many people i know.
however, im not sure how hard it might be to implement support for it, since its software is prolly not the same as apple's Messages...

**Comment by treason** [comment]
Yea, the reason for WifiSMS in my opinion is because apple doesnt allow devs to access the SMS.db, otherwise this would have been on appstore a long time ago.

There is nothing stopping WhatsApp from running a web server like mine in their own software and it would totally be fine with apples guidelines. So, I think this is a feature request for Whatsapp, not WifiSMS.
