### ISSUE TITLE
User is forced to install SBSettings and other stuff

### ISSUE THREAD

**Issue by piejanssens** [jlippold/WifiSMS#51]
I don't use SBSettings since I use IntelliscreenX which has everything I need. You shouldn't make SBSettings a dependency and create a seperate package for the sbsettings toggle.

**Comment by vampirehim** [comment]
Same here I don't use SBSettings either or any of the other stuff. Would be nice to remove all the other stuff :/

**Comment by fopina** [comment]
you can always use the NoSBS package treason has here instead of going through Cydia :)

**Comment by vampirehim** [comment]
If you could help me how would I go about installing that?

**Comment by fopina** [comment]
- Download the deb file
- Copy it to your device (SCP, iFunBox, iExplorer)
- Login through SSH and run `dpkg -i whatever.deb`
