### ISSUE TITLE
International Sending (again)

### ISSUE THREAD

**Issue by RexNoctis** [jlippold/WifiSMS#6]
Hi,

I'm in the UK and having trouble sending messages. I've upgraded to v1.0.4 through Cydia which didn't work so I uninstalled and reinstalled WifiSMS. After reinstallation, no contacts are shown, only the phone numbers and sent messages are still not arriving. 

I'll be able to tell you what number 02 (service provider) think the messages  have been sent to in about 24 hours when the online account pages are updated. It was through these pages I realised messages were being sent with the US country code (and I was hence being charged for them)

As an aside, this may be of help: Once WifiSMS was uninstalled, browsing to the phone just produced a blank webpage, NOT the 'request rejected' page that appears when WifiSMS is switched off or I attempt to browse to a random port on the iPhone. Does this mean WifiSMS was not fully removed?

I love the idea of WifiSMS and really hope I can get it working. Would be happy to help with beta testing and webpage development if needed! I appreciate this is a weekend effort and would like to thank you for the work you have done!

Cheers!

**Comment by treason** [comment]
yea this country code shit is a real drag... i dont even know where to begin. I have some people from the UK who say it's fine and others who say it's broken..

I dont know how to fix it, but I am open to ideas

**Comment by treason** [comment]
try 1.0.5 maybe it is fixed
