### ISSUE TITLE
Ability to access WifiSMS over data IP

### ISSUE THREAD

**Issue by bhendel-zz** [jlippold/WifiSMS#67]
I am not sure if this is an intentional restriction, or a restriction of the data network, but WifiSMS does not respond on it's pubic data IP, like it does on it's private LAN IP. Thoughts?

Thanks!

-Brian

**Comment by fopina** [comment]
It must be a restriction on your network because it works just fine here (disconnected iPhone from Wifi and accessed WifiSMS using its 3G network IP).

**Comment by bhendel-zz** [comment]
Interesting. Do you have to disconnect from WiFi to have the app listen on the data IP, or can you access WifiSMS on either IP at the same time?  What port are you using?  8080 over here.

-Brian

**Comment by fopina** [comment]
I never use standard ports, even more if I would use it open on the internet. And yes, I can access using public IP even if Wifi is also connected.
Try changing the port, maybe your data provider blocks 8080 (as it's a common port for proxies and etc). But it's not an issue in WifiSMS.

**Comment by bhendel-zz** [comment]
Changed port to 50xxx, restarted, listens fine on it's 192.168.x.x address, but not on Telus's 10.206.x.x data address. Has anyone noticed Cell providers firewalling incoming connections?

**Comment by fopina** [comment]
You know that 10.x.x.x are internal IPs right? So that means your data provider does not assign public IPs to each device.

**Comment by bhendel-zz** [comment]
Duh, you are right.   The public facing IPs come out as 72.38.x.x but that is just a gateway router. Bummer.  I guess it is a bit safer this way, but unfortunate. 

Thanks for the help.
