### ISSUE TITLE
It doesn't handle Iphone Delivery.

### ISSUE THREAD

**Issue by Spidored** [jlippold/WifiSMS#7]
Hi, i really enjoy this app, it's just a little thing not really matter, but on my phone i always install "iPhone delivery" that put an "V" or "X" or "..." just next to the SMS to say if it's in courses, received or failed.

Delivery notification so.

When i send with my iPhone (biteSMS) it work properly, i got the V/X/... but when i send it with WifiSMS http, i got the delivery report notification, but the V/X/... doesn't appear in the conversation (inside the iPhone i mean).

Maybe there's a way to use it ? and better, maybe there's a way to put a V/X/... inside the WifiSMS http.
(I think when iPhone delivery is installed, it add a field in the sms.db, so it's not really hard to handle, maybe i'm wrong).

**Comment by treason** [comment]
If thats true, I could probably do it... Are you sure it's just a field in the SMS.db? Do you know how to access the SMS.db to confirm that it's jsut another field in the table? Thanks

**Comment by Spidored** [comment]
yep, it's a field, "dr_date" it will be empty if the message not received yet. But i don't understand why the field doesn't set when i send with WifiSMS instead of biteSMS. Maybe there's something to do when the sms is sending... can't find the reason why. 

Maybe u can find that in the code of iphoneDelivery https://code.google.com/ or else asking how it "work" (from DB or else) to the owner.

but it's a little thing, i don't really care if it's not implemented ^^

**Comment by Spidored** [comment]
i have open an issue on the tracker of iphone delivery to figured out how it work, i stay u in touch ;) thanks again for ur support

**Comment by treason** [comment]
Lol if that's that case I won't do it. I don't use it either... I probably set the field as null, maybe it expects and empty string or something like that?

**Comment by treason** [comment]
1.0.5 is sending SMS in a different way. this might fix itself. try 1.0.5 to be certain

**Comment by Spidored** [comment]
Yes i confirm, the V/X/... is appearing in my sms app =)

**Comment by treason** [comment]
Nice thanks
