### ISSUE TITLE
refresh the left side too

### ISSUE THREAD

**Issue by Spidored** [jlippold/WifiSMS#8]
When a SMS is received, the app play a sound, and add "+1" on the left side (contact frame). Maybe we can do a refresh of that frame to get up the order of the contact. 

Ex of a frame bar : 

Contact 1
Contact 5
Contact 2
Contact 4
Contact 3

(appear by last received message order)

When we received a message from Contact 2 it goes like this : 

Contact 1
Contact 5
(+1) Contact 2
Contact 4
Contact 3

I think it would be better to do this directly

(+1) Contact 2
Contact 1
Contact 5
Contact 4
Contact 3

It will be great cause when we have a lot of contact on the left, and a new SMS from a contact who's on the end of the list, we don't see it easily. 

Thanks for ur listening ^^

Spido.

**Comment by treason** [comment]
Yes ur right on this. I need to get sorting of the list down. I tried it in the beginning and stopped, I'll take another look

**Comment by treason** [comment]
Fixed in 1.0.5

**Comment by treason** [comment]
Would you try 1.0.5 and confirm fixed? https://github.com/treason/WifiSMS/blob/master/Build/deb/WifiSMS-NOSBS-1.0.5.deb?raw=true

**Comment by Spidored** [comment]
i'll try this afternoon, i'll keep u in touch :-)

**Comment by Spidored** [comment]
i tried, perfectly working.
